mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from . import views

urlpatterns = [
	path('', views.home, name='home'),
	path('scrape/', include('scrape.urls')),
	path('polls/', include('polls.urls')),
	path('odds/', include('odds.urls')),
    path('admin/', admin.site.urls),
]

mysite/odds/urls.py
from django.urls import path
from . import views

app_name = 'odds'

urlpatterns = [
	path('', views.index, name='index'),
	path('playersearch/', views.player_search, name='player_search'),
	path('results/', views.results, name='results'),
]

mysite/polls/urls.py
from django.urls import path
from . import views

app_name = 'polls'
urlpatterns = [
	path('', views.IndexView.as_view(), name='index'),
	path('add', views.add, name='add'),
	path('<int:pk>/', views.DetailView.as_view(), name='detail'),
	path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
	path('<int:question_id>/vote/', views.vote, name='vote'),
]

mysite/polls/models.py
import datetime
from django.db import models
from django.utils import timezone

# Create your models here.
class Question(models.Model):
	question_text = models.CharField(max_length=200)
	pub_date = models.DateTimeField('date published')
	def __str__(self):
		return self.question_text
	def was_published_recently(self):
		now = timezone.now()
		return now - datetime.timedelta(days=1) <= self.pub_date <= now

class Choice(models.Model):
	question = models.ForeignKey(Question, on_delete=models.CASCADE)
	choice_text = models.CharField(max_length=200)
	votes = models.IntegerField(default=0)
	def __str__(self):
		return self.choice_text

mysite/polls/views.py
from django.shortcuts import get_object_or_404, render
from .models import Question, Choice
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views import generic
from django.utils import timezone
import bleach

class IndexView(generic.ListView):
	template_name = 'polls/index.html'
	context_object_name = 'latest_question_list'
	
	def get_queryset(self):
		return Question.objects.filter(pub_date__lte=timezone.now()).order_by('-pub_date')[:5]
		
class DetailView(generic.DetailView):
	model = Question
	template_name = 'polls/detail.html'
	def get_queryset(self):
		return Question.objects.filter(pub_date__lte=timezone.now())
	
class ResultsView(generic.DetailView):
	model = Question
	template_name = 'polls/results.html'

def vote(request, question_id):
	question = get_object_or_404(Question, pk=question_id)
	try:
		selected_choice = question.choice_set.get(pk=request.POST['choice'])
	except (KeyError, Choice.DoesNotExist):
		return render(request, 'polls/detail.html',{'question':question,'error_message':"You didn't select a choice.",})
	else:
		selected_choice.votes += 1
		selected_choice.save()
		#always do so no double post
		return HttpResponseRedirect(reverse('polls:results',args=(question.id,)))
	
def add(request):
	if request.method == 'POST':
		sentence = request.POST.get('question',None)
		question = bleach.clean(sentence)
		one = request.POST.get('one',None)
		two = request.POST.get('two',None)
		three = request.POST.get('three',None)
		four = request.POST.get('four',None)
		add_Quest = Question(question_text=question, pub_date=timezone.now())
		add_Quest.save()
		if one:
			add_Quest.choice_set.create(choice_text=one, votes=0)
		if two:
			add_Quest.choice_set.create(choice_text=two, votes=0)
		if three:
			add_Quest.choice_set.create(choice_text=three, votes=0)
		if four:
			add_Quest.choice_set.create(choice_text=four, votes=0)
		if add_Quest.choice_set.count() == 0:
			add_Quest.choice_set.create(choice_text="Yes", votes=0)
			add_Quest.choice_set.create(choice_text="Maybe", votes=0)
			add_Quest.choice_set.create(choice_text="No.", votes=0)
		return HttpResponseRedirect(reverse('polls:detail',args=(add_Quest.id,)))
	else:
		return render(request, 'polls/add.html')

mysite/polls/templates/polls/add.html
<!DOCTYPE html>
<head>
<title>Poll Results</title>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
</head>
<body style='background-color:#DDD'>
	<div class='container text-center'>
		<div class='row'>
			<div class='col-lg-12 col-xs-4'>
				<h1 class='my-5'>Ask Away!</h1>
				<form method="POST" action="/polls/add" class='my-3 py-4'>
				{% csrf_token %}
				<textarea class='m-2' type="textarea" name="question" placeholder="?"></textarea>
				<br>
				<input class='m-2' type="text" name="one" placeholder="Choice 1">
				<input class='m-2' type="text" name="two" placeholder="Choice 2">
				<input class='m-2' type="text" name="three" placeholder="Choice 3">
				<input class='m-2' type="text" name="four" placeholder="Choice 4">
				<br>
				<button class='my-5 btn btn-primary' type="submit">Submit</button>
				</form>
				<a href="/polls"><button class='my-5 btn btn-danger'>Go Back</button></a>
			</div>
		</div>
	</div>

mysite/polls/templates/polls/detail.html
<!DOCTYPE html>
<head>
<title>Poll Results</title>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
</head>
<body style='background-color:#DDD'>
	<div class='container text-center'>
		<div class='row'>
			<div class='col-lg-12 col-xs-4'>
				<h1 class='my-5' >{{ question.question_text }}</h1>
				{% if error_message %}<p><strong>{{error_message}}</strong></p>{% endif %}
				<form class='bg-light pt-3' action="{% url 'polls:vote' question.id %}" method="post">
				{% csrf_token %}
				{% for choice in question.choice_set.all %}
					<input type="radio" name="choice" id="choice {{ forloop.counter }}" value="{{ choice.id }}">
					<label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label>
				<br>
				{% endfor %}
				<input class='my-3 btn btn-success' type="submit" value="Vote">
				</form>
			</div>
		</div>
	</div>

mysite/polls/templates/polls/index.html
<!DOCTYPE html>
<head>
<title>Poll Results</title>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
</head>
<body style='background-color:#DDD'>
	<div class='container text-center'>
		<div class='row'>
			<div class='col-lg-12 col-xs-4'>
				<h1 class='my-5'>Latest Questions to Vote on</h1>
				{% if latest_question_list %}
					<ul>
					{% for question in latest_question_list %}
						<li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
					{% endfor %}
					</ul>
				{% else %}
					<p>No polls are available.</p>
				{% endif %}
				<a href="add"><button class='my-5 btn btn-success'>Add Question</button></a>
			</div>
		</div>
	</div>

mysite/polls/templates/polls/results.html
<!DOCTYPE html>
<head>
<title>Poll Results</title>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
</head>
<body style='background-color:#DDD'>
	<div class='container text-center'>
		<div class='row'>
			<div class='col-lg-12 col-xs-4'>
			<h1 class='my-5'>{{ question.question_text }}</h1>
			<ul class='p-3' style='list-style:none; background-color:aliceblue'>
			{% for choice in question.choice_set.all %}
				<li class='my-2'>{{ choice.choice_text }} --- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
			{% endfor %}
			</ul>

			<a href="{% url 'polls:detail' question.id %}"><button class='btn btn-primary'>Vote Again?</button></a>
			</div>
		</div>
	</div>